server:
  port: 1000

spring:
  application:
    name: app-gateway
  cloud:
    gateway:
#      default-filters:
#        - PrefixPath=/app-user
#        - AddResponseHeader=X-Response-Default-Foo, Default-Bar
      routes:
      - id: app-admin-service
        uri: http://127.0.0.1:4000/
        predicates:
        - Path=/app-user/*
        filters:
        - name: RequestRateLimiter
          args:
            redis-rate-limiter.replenishRate: 10
            redis-rate-limiter.burstCapacity: 20
            redis-rate-limiter.requestedTokens: 1

  jmx:
    enabled: true
  redis:
    host: 111.231.215.20
    port: 7777
    database: 0
    password: C..liizhou1!!

eureka:
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:30000/eureka/
  instance:
    instance-id: ${spring.application.name}
    hostname: 127.0.0.1



management:
  server:
    port: 11000
  endpoint:
    beans:
      enabled: true
      cache:
        time-to-live: 1000ms
    health:
      show-details: always
    shutdown:
      enabled: true
    jolokia:
      enabled: true
      config:
        debug: true
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"
        exclude: env,beans
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG