server:
  servlet:
    context-path: /user-auth-server
spring:
  application:
    name: ${APP_NAME:user-auth-server}
  profiles:
    active: local
  jmx:
    enabled: true
  jackson:
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://${MYSQL_SERVER:127.0.0.1}:${MYSQL_PORT:8888}/guide?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8
    username: ENC(uSpU5irKuvMIT1mR0/2Whgh3EY9dRKwNKkZBNh2z20h4T8Le8SGPYBzC957M0hGS)
    password: ENC(Y5xuHdnuK897yMFWFJQA3ZFT7+Z4YCVvnp/st/SlgNw54YmOpD0qIYFBcmLry2Ks)
    hikari:
      pool-name: ${spring.application.name}-pool
      maximum-pool-size: 20
      minimum-idle: 3
      max-lifetime: 30000
      connection-test-query: select 1
  redis:
    host: 111.231.215.20
    port: 7777
    database: 0
    password: ENC(EY7Y4OEBEg5n/nZdeNYO1FEBAbGWrehdKyTzHNak3g3zRLFxw0BWajW6TDz0JX/K)
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql

eureka:
  instance:
    statusPageUrlPath: /actuator/info
    healthCheckUrlPath: /actuator/health
    hostname: 127.0.0.1
  #    instance-id: ${spring.application.name}
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://${REGISTER_HOST_NAME:localhost}:${REGISTER_APP_PORT:3000}/eureka/
management:
  endpoint:
    beans:
      enabled: true
      cache:
        time-to-live: 1000ms
    health:
      show-details: always
    shutdown:
      enabled: true
    jolokia:
      enabled: true
      config:
        debug: true
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"
        exclude: env,beans



logging:
  config: classpath:logback-spring.xml



feign:
  okhttp:
    enabled: true
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: FULL  # BASIC, FULL, HEADERS, NONE

---
spring:
  profiles: local
  devtools:
    livereload:
      port: ${DEV_TOOLS_PORT:52005}
management:
  server:
    port: ${MANAGEMENT_PORT:51005}
server:
  port: ${APP_PORT:5005}

---
spring:
  profiles: dev
  devtools:
    livereload:
      port: ${DEV_TOOLS_PORT:52006}
management:
  server:
    port: ${MANAGEMENT_PORT:51006}
server:
  port: ${APP_PORT:5006}


---
spring:
  profiles: prod
  devtools:
    livereload:
      port: ${DEV_TOOLS_PORT:52007}
management:
  server:
    port: ${MANAGEMENT_PORT:51007}
server:
  port: ${APP_PORT:5007}