/*
 * This file is generated by jOOQ.
 */
package com.klaus.iv.stockadmin.db.tables;


import com.klaus.iv.stockadmin.db.Guide;
import com.klaus.iv.stockadmin.db.Keys;
import com.klaus.iv.stockadmin.db.tables.records.StockGroupRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row10;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StockGroup extends TableImpl<StockGroupRecord> {

    private static final long serialVersionUID = 1919444634;

    /**
     * The reference instance of <code>guide.stock_group</code>
     */
    public static final StockGroup STOCK_GROUP = new StockGroup();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<StockGroupRecord> getRecordType() {
        return StockGroupRecord.class;
    }

    /**
     * The column <code>guide.stock_group.id</code>.
     */
    public final TableField<StockGroupRecord, Long> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>guide.stock_group.create_by</code>.
     */
    public final TableField<StockGroupRecord, Long> CREATE_BY = createField(DSL.name("create_by"), org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>guide.stock_group.create_dt</code>.
     */
    public final TableField<StockGroupRecord, LocalDateTime> CREATE_DT = createField(DSL.name("create_dt"), org.jooq.impl.SQLDataType.LOCALDATETIME, this, "");

    /**
     * The column <code>guide.stock_group.is_delete</code>.
     */
    public final TableField<StockGroupRecord, Integer> IS_DELETE = createField(DSL.name("is_delete"), org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>guide.stock_group.update_by</code>.
     */
    public final TableField<StockGroupRecord, Long> UPDATE_BY = createField(DSL.name("update_by"), org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>guide.stock_group.update_dt</code>.
     */
    public final TableField<StockGroupRecord, LocalDateTime> UPDATE_DT = createField(DSL.name("update_dt"), org.jooq.impl.SQLDataType.LOCALDATETIME, this, "");

    /**
     * The column <code>guide.stock_group.add_comments</code>.
     */
    public final TableField<StockGroupRecord, String> ADD_COMMENTS = createField(DSL.name("add_comments"), org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>guide.stock_group.group_code</code>.
     */
    public final TableField<StockGroupRecord, String> GROUP_CODE = createField(DSL.name("group_code"), org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>guide.stock_group.price</code>.
     */
    public final TableField<StockGroupRecord, Long> PRICE = createField(DSL.name("price"), org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>guide.stock_group.stock_code</code>.
     */
    public final TableField<StockGroupRecord, String> STOCK_CODE = createField(DSL.name("stock_code"), org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * Create a <code>guide.stock_group</code> table reference
     */
    public StockGroup() {
        this(DSL.name("stock_group"), null);
    }

    /**
     * Create an aliased <code>guide.stock_group</code> table reference
     */
    public StockGroup(String alias) {
        this(DSL.name(alias), STOCK_GROUP);
    }

    /**
     * Create an aliased <code>guide.stock_group</code> table reference
     */
    public StockGroup(Name alias) {
        this(alias, STOCK_GROUP);
    }

    private StockGroup(Name alias, Table<StockGroupRecord> aliased) {
        this(alias, aliased, null);
    }

    private StockGroup(Name alias, Table<StockGroupRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> StockGroup(Table<O> child, ForeignKey<O, StockGroupRecord> key) {
        super(child, key, STOCK_GROUP);
    }

    @Override
    public Schema getSchema() {
        return Guide.GUIDE;
    }

    @Override
    public Identity<StockGroupRecord, Long> getIdentity() {
        return Keys.IDENTITY_STOCK_GROUP;
    }

    @Override
    public UniqueKey<StockGroupRecord> getPrimaryKey() {
        return Keys.KEY_STOCK_GROUP_PRIMARY;
    }

    @Override
    public List<UniqueKey<StockGroupRecord>> getKeys() {
        return Arrays.<UniqueKey<StockGroupRecord>>asList(Keys.KEY_STOCK_GROUP_PRIMARY);
    }

    @Override
    public StockGroup as(String alias) {
        return new StockGroup(DSL.name(alias), this);
    }

    @Override
    public StockGroup as(Name alias) {
        return new StockGroup(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public StockGroup rename(String name) {
        return new StockGroup(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public StockGroup rename(Name name) {
        return new StockGroup(name, null);
    }

    // -------------------------------------------------------------------------
    // Row10 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row10<Long, Long, LocalDateTime, Integer, Long, LocalDateTime, String, String, Long, String> fieldsRow() {
        return (Row10) super.fieldsRow();
    }
}
