/*
 * This file is generated by jOOQ.
 */
package com.klaus.iv.stockadmin.db.tables;


import com.klaus.iv.stockadmin.db.Guide;
import com.klaus.iv.stockadmin.db.Keys;
import com.klaus.iv.stockadmin.db.tables.records.StockPoRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row9;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StockPo extends TableImpl<StockPoRecord> {

    private static final long serialVersionUID = -1883456247;

    /**
     * The reference instance of <code>guide.stock_po</code>
     */
    public static final StockPo STOCK_PO = new StockPo();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<StockPoRecord> getRecordType() {
        return StockPoRecord.class;
    }

    /**
     * The column <code>guide.stock_po.id</code>.
     */
    public final TableField<StockPoRecord, Long> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>guide.stock_po.create_by</code>.
     */
    public final TableField<StockPoRecord, Long> CREATE_BY = createField(DSL.name("create_by"), org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>guide.stock_po.create_dt</code>.
     */
    public final TableField<StockPoRecord, LocalDateTime> CREATE_DT = createField(DSL.name("create_dt"), org.jooq.impl.SQLDataType.LOCALDATETIME, this, "");

    /**
     * The column <code>guide.stock_po.is_delete</code>.
     */
    public final TableField<StockPoRecord, Integer> IS_DELETE = createField(DSL.name("is_delete"), org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>guide.stock_po.update_by</code>.
     */
    public final TableField<StockPoRecord, Long> UPDATE_BY = createField(DSL.name("update_by"), org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>guide.stock_po.update_dt</code>.
     */
    public final TableField<StockPoRecord, LocalDateTime> UPDATE_DT = createField(DSL.name("update_dt"), org.jooq.impl.SQLDataType.LOCALDATETIME, this, "");

    /**
     * The column <code>guide.stock_po.code</code>.
     */
    public final TableField<StockPoRecord, String> CODE = createField(DSL.name("code"), org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>guide.stock_po.name</code>.
     */
    public final TableField<StockPoRecord, String> NAME = createField(DSL.name("name"), org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>guide.stock_po.stock_desc</code>.
     */
    public final TableField<StockPoRecord, String> STOCK_DESC = createField(DSL.name("stock_desc"), org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * Create a <code>guide.stock_po</code> table reference
     */
    public StockPo() {
        this(DSL.name("stock_po"), null);
    }

    /**
     * Create an aliased <code>guide.stock_po</code> table reference
     */
    public StockPo(String alias) {
        this(DSL.name(alias), STOCK_PO);
    }

    /**
     * Create an aliased <code>guide.stock_po</code> table reference
     */
    public StockPo(Name alias) {
        this(alias, STOCK_PO);
    }

    private StockPo(Name alias, Table<StockPoRecord> aliased) {
        this(alias, aliased, null);
    }

    private StockPo(Name alias, Table<StockPoRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> StockPo(Table<O> child, ForeignKey<O, StockPoRecord> key) {
        super(child, key, STOCK_PO);
    }

    @Override
    public Schema getSchema() {
        return Guide.GUIDE;
    }

    @Override
    public Identity<StockPoRecord, Long> getIdentity() {
        return Keys.IDENTITY_STOCK_PO;
    }

    @Override
    public UniqueKey<StockPoRecord> getPrimaryKey() {
        return Keys.KEY_STOCK_PO_PRIMARY;
    }

    @Override
    public List<UniqueKey<StockPoRecord>> getKeys() {
        return Arrays.<UniqueKey<StockPoRecord>>asList(Keys.KEY_STOCK_PO_PRIMARY);
    }

    @Override
    public StockPo as(String alias) {
        return new StockPo(DSL.name(alias), this);
    }

    @Override
    public StockPo as(Name alias) {
        return new StockPo(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public StockPo rename(String name) {
        return new StockPo(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public StockPo rename(Name name) {
        return new StockPo(name, null);
    }

    // -------------------------------------------------------------------------
    // Row9 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row9<Long, Long, LocalDateTime, Integer, Long, LocalDateTime, String, String, String> fieldsRow() {
        return (Row9) super.fieldsRow();
    }
}
