/*
 * This file is generated by jOOQ.
 */
package com.klaus.iv.stockadmin.db.tables;


import com.klaus.iv.stockadmin.db.Guide;
import com.klaus.iv.stockadmin.db.Keys;
import com.klaus.iv.stockadmin.db.tables.records.StockRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row9;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Stock extends TableImpl<StockRecord> {

    private static final long serialVersionUID = 414144708;

    /**
     * The reference instance of <code>guide.stock</code>
     */
    public static final Stock STOCK = new Stock();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<StockRecord> getRecordType() {
        return StockRecord.class;
    }

    /**
     * The column <code>guide.stock.id</code>.
     */
    public final TableField<StockRecord, Long> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>guide.stock.create_by</code>.
     */
    public final TableField<StockRecord, Long> CREATE_BY = createField(DSL.name("create_by"), org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>guide.stock.create_dt</code>.
     */
    public final TableField<StockRecord, LocalDateTime> CREATE_DT = createField(DSL.name("create_dt"), org.jooq.impl.SQLDataType.LOCALDATETIME, this, "");

    /**
     * The column <code>guide.stock.is_delete</code>.
     */
    public final TableField<StockRecord, Integer> IS_DELETE = createField(DSL.name("is_delete"), org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>guide.stock.update_by</code>.
     */
    public final TableField<StockRecord, Long> UPDATE_BY = createField(DSL.name("update_by"), org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>guide.stock.update_dt</code>.
     */
    public final TableField<StockRecord, LocalDateTime> UPDATE_DT = createField(DSL.name("update_dt"), org.jooq.impl.SQLDataType.LOCALDATETIME, this, "");

    /**
     * The column <code>guide.stock.code</code>.
     */
    public final TableField<StockRecord, String> CODE = createField(DSL.name("code"), org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>guide.stock.name</code>.
     */
    public final TableField<StockRecord, String> NAME = createField(DSL.name("name"), org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>guide.stock.stock_desc</code>.
     */
    public final TableField<StockRecord, String> STOCK_DESC = createField(DSL.name("stock_desc"), org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * Create a <code>guide.stock</code> table reference
     */
    public Stock() {
        this(DSL.name("stock"), null);
    }

    /**
     * Create an aliased <code>guide.stock</code> table reference
     */
    public Stock(String alias) {
        this(DSL.name(alias), STOCK);
    }

    /**
     * Create an aliased <code>guide.stock</code> table reference
     */
    public Stock(Name alias) {
        this(alias, STOCK);
    }

    private Stock(Name alias, Table<StockRecord> aliased) {
        this(alias, aliased, null);
    }

    private Stock(Name alias, Table<StockRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> Stock(Table<O> child, ForeignKey<O, StockRecord> key) {
        super(child, key, STOCK);
    }

    @Override
    public Schema getSchema() {
        return Guide.GUIDE;
    }

    @Override
    public Identity<StockRecord, Long> getIdentity() {
        return Keys.IDENTITY_STOCK;
    }

    @Override
    public UniqueKey<StockRecord> getPrimaryKey() {
        return Keys.KEY_STOCK_PRIMARY;
    }

    @Override
    public List<UniqueKey<StockRecord>> getKeys() {
        return Arrays.<UniqueKey<StockRecord>>asList(Keys.KEY_STOCK_PRIMARY);
    }

    @Override
    public Stock as(String alias) {
        return new Stock(DSL.name(alias), this);
    }

    @Override
    public Stock as(Name alias) {
        return new Stock(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Stock rename(String name) {
        return new Stock(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Stock rename(Name name) {
        return new Stock(name, null);
    }

    // -------------------------------------------------------------------------
    // Row9 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row9<Long, Long, LocalDateTime, Integer, Long, LocalDateTime, String, String, String> fieldsRow() {
        return (Row9) super.fieldsRow();
    }
}
