/*
 * This file is generated by jOOQ.
 */
package com.klaus.iv.useradmin.db;


import com.klaus.iv.useradmin.db.tables.Address;
import com.klaus.iv.useradmin.db.tables.Resource;
import com.klaus.iv.useradmin.db.tables.Role;
import com.klaus.iv.useradmin.db.tables.RoleResource;
import com.klaus.iv.useradmin.db.tables.User;
import com.klaus.iv.useradmin.db.tables.UserAddress;
import com.klaus.iv.useradmin.db.tables.UserExt;
import com.klaus.iv.useradmin.db.tables.UserRole;


/**
 * Convenience access to all tables in user_center
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>user_center.address</code>.
     */
    public static final Address ADDRESS = Address.ADDRESS;

    /**
     * The table <code>user_center.resource</code>.
     */
    public static final Resource RESOURCE = Resource.RESOURCE;

    /**
     * The table <code>user_center.role</code>.
     */
    public static final Role ROLE = Role.ROLE;

    /**
     * The table <code>user_center.role_resource</code>.
     */
    public static final RoleResource ROLE_RESOURCE = RoleResource.ROLE_RESOURCE;

    /**
     * The table <code>user_center.user</code>.
     */
    public static final User USER = User.USER;

    /**
     * The table <code>user_center.user_address</code>.
     */
    public static final UserAddress USER_ADDRESS = UserAddress.USER_ADDRESS;

    /**
     * The table <code>user_center.user_ext</code>.
     */
    public static final UserExt USER_EXT = UserExt.USER_EXT;

    /**
     * The table <code>user_center.user_role</code>.
     */
    public static final UserRole USER_ROLE = UserRole.USER_ROLE;
}
