/*
 * This file is generated by jOOQ.
 */
package com.klaus.iv.useradmin.db;


import com.klaus.iv.useradmin.db.tables.Address;
import com.klaus.iv.useradmin.db.tables.Resource;
import com.klaus.iv.useradmin.db.tables.Role;
import com.klaus.iv.useradmin.db.tables.RoleResource;
import com.klaus.iv.useradmin.db.tables.User;
import com.klaus.iv.useradmin.db.tables.UserAddress;
import com.klaus.iv.useradmin.db.tables.UserExt;
import com.klaus.iv.useradmin.db.tables.UserRole;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserCenter extends SchemaImpl {

    private static final long serialVersionUID = 286095259;

    /**
     * The reference instance of <code>user_center</code>
     */
    public static final UserCenter USER_CENTER = new UserCenter();

    /**
     * The table <code>user_center.address</code>.
     */
    public final Address ADDRESS = Address.ADDRESS;

    /**
     * The table <code>user_center.resource</code>.
     */
    public final Resource RESOURCE = Resource.RESOURCE;

    /**
     * The table <code>user_center.role</code>.
     */
    public final Role ROLE = Role.ROLE;

    /**
     * The table <code>user_center.role_resource</code>.
     */
    public final RoleResource ROLE_RESOURCE = RoleResource.ROLE_RESOURCE;

    /**
     * The table <code>user_center.user</code>.
     */
    public final User USER = User.USER;

    /**
     * The table <code>user_center.user_address</code>.
     */
    public final UserAddress USER_ADDRESS = UserAddress.USER_ADDRESS;

    /**
     * The table <code>user_center.user_ext</code>.
     */
    public final UserExt USER_EXT = UserExt.USER_EXT;

    /**
     * The table <code>user_center.user_role</code>.
     */
    public final UserRole USER_ROLE = UserRole.USER_ROLE;

    /**
     * No further instances allowed
     */
    private UserCenter() {
        super("user_center", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Address.ADDRESS,
            Resource.RESOURCE,
            Role.ROLE,
            RoleResource.ROLE_RESOURCE,
            User.USER,
            UserAddress.USER_ADDRESS,
            UserExt.USER_EXT,
            UserRole.USER_ROLE);
    }
}
