spring:
  jmx:
    enabled: true
  jackson:
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://${MYSQL_SERVER:212.129.238.215}:${MYSQL_PORT:8888}/user_center?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8
    #username: guide
    #password: Z..li1zh@u1!!
    username: ENC(uSpU5irKuvMIT1mR0/2Whgh3EY9dRKwNKkZBNh2z20h4T8Le8SGPYBzC957M0hGS)
    password: ENC(Y5xuHdnuK897yMFWFJQA3ZFT7+Z4YCVvnp/st/SlgNw54YmOpD0qIYFBcmLry2Ks)
    hikari:
      pool-name: ${spring.application.name}-pool
      maximum-pool-size: 20
      minimum-idle: 3
      max-lifetime: 30000
      connection-test-query: select 1
  redis:
    host: 111.231.215.20
    port: 7777
    database: 0
    #password: C..liizhou1!!
    password: ENC(EY7Y4OEBEg5n/nZdeNYO1FEBAbGWrehdKyTzHNak3g3zRLFxw0BWajW6TDz0JX/K)
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
  jooq:
    sql-dialect: mariadb

logging:
  config: classpath:logback-spring.xml



feign:
  okhttp:
    enabled: true
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: FULL  # BASIC, FULL, HEADERS, NONE

---
spring:
  profiles: local
  devtools:
    livereload:
      port: ${DEV_TOOLS_PORT:42005}
management:
  server:
    port: ${MANAGEMENT_PORT:41005}
server:
  port: ${APP_PORT:4005}

---
spring:
  profiles: dev
  devtools:
    livereload:
      port: ${DEV_TOOLS_PORT:42006}
management:
  server:
    port: ${MANAGEMENT_PORT:41006}
server:
  port: ${APP_PORT:4006}


---
spring:
  profiles: prod
  devtools:
    livereload:
      port: ${DEV_TOOLS_PORT:42007}
management:
  server:
    port: ${MANAGEMENT_PORT:41007}
server:
  port: ${APP_PORT:4007}