/*
 * This file is generated by jOOQ.
 */
package com.klaus.iv.stockadmin.db.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StockGroup implements Serializable {

    private static final long serialVersionUID = -636077073;

    private Long          id;
    private Long          createBy;
    private LocalDateTime createDt;
    private Integer       isDelete;
    private Long          updateBy;
    private LocalDateTime updateDt;
    private String        addComments;
    private String        groupCode;
    private Long          price;
    private String        stockCode;

    public StockGroup() {}

    public StockGroup(StockGroup value) {
        this.id = value.id;
        this.createBy = value.createBy;
        this.createDt = value.createDt;
        this.isDelete = value.isDelete;
        this.updateBy = value.updateBy;
        this.updateDt = value.updateDt;
        this.addComments = value.addComments;
        this.groupCode = value.groupCode;
        this.price = value.price;
        this.stockCode = value.stockCode;
    }

    public StockGroup(
        Long          id,
        Long          createBy,
        LocalDateTime createDt,
        Integer       isDelete,
        Long          updateBy,
        LocalDateTime updateDt,
        String        addComments,
        String        groupCode,
        Long          price,
        String        stockCode
    ) {
        this.id = id;
        this.createBy = createBy;
        this.createDt = createDt;
        this.isDelete = isDelete;
        this.updateBy = updateBy;
        this.updateDt = updateDt;
        this.addComments = addComments;
        this.groupCode = groupCode;
        this.price = price;
        this.stockCode = stockCode;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getCreateBy() {
        return this.createBy;
    }

    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }

    public LocalDateTime getCreateDt() {
        return this.createDt;
    }

    public void setCreateDt(LocalDateTime createDt) {
        this.createDt = createDt;
    }

    public Integer getIsDelete() {
        return this.isDelete;
    }

    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    public Long getUpdateBy() {
        return this.updateBy;
    }

    public void setUpdateBy(Long updateBy) {
        this.updateBy = updateBy;
    }

    public LocalDateTime getUpdateDt() {
        return this.updateDt;
    }

    public void setUpdateDt(LocalDateTime updateDt) {
        this.updateDt = updateDt;
    }

    public String getAddComments() {
        return this.addComments;
    }

    public void setAddComments(String addComments) {
        this.addComments = addComments;
    }

    public String getGroupCode() {
        return this.groupCode;
    }

    public void setGroupCode(String groupCode) {
        this.groupCode = groupCode;
    }

    public Long getPrice() {
        return this.price;
    }

    public void setPrice(Long price) {
        this.price = price;
    }

    public String getStockCode() {
        return this.stockCode;
    }

    public void setStockCode(String stockCode) {
        this.stockCode = stockCode;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("StockGroup (");

        sb.append(id);
        sb.append(", ").append(createBy);
        sb.append(", ").append(createDt);
        sb.append(", ").append(isDelete);
        sb.append(", ").append(updateBy);
        sb.append(", ").append(updateDt);
        sb.append(", ").append(addComments);
        sb.append(", ").append(groupCode);
        sb.append(", ").append(price);
        sb.append(", ").append(stockCode);

        sb.append(")");
        return sb.toString();
    }
}
