/*
 * This file is generated by jOOQ.
 */
package com.klaus.iv.stockadmin.db.tables.records;


import com.klaus.iv.stockadmin.db.tables.Address;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record15;
import org.jooq.Row15;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AddressRecord extends UpdatableRecordImpl<AddressRecord> implements Record15<Long, Long, LocalDateTime, Integer, Long, LocalDateTime, String, String, String, String, String, String, String, Integer, String> {

    private static final long serialVersionUID = -2018089284;

    /**
     * Setter for <code>guide.address.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>guide.address.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>guide.address.create_by</code>.
     */
    public void setCreateBy(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>guide.address.create_by</code>.
     */
    public Long getCreateBy() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>guide.address.create_dt</code>.
     */
    public void setCreateDt(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>guide.address.create_dt</code>.
     */
    public LocalDateTime getCreateDt() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>guide.address.is_delete</code>.
     */
    public void setIsDelete(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>guide.address.is_delete</code>.
     */
    public Integer getIsDelete() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>guide.address.update_by</code>.
     */
    public void setUpdateBy(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>guide.address.update_by</code>.
     */
    public Long getUpdateBy() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>guide.address.update_dt</code>.
     */
    public void setUpdateDt(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>guide.address.update_dt</code>.
     */
    public LocalDateTime getUpdateDt() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>guide.address.city</code>.
     */
    public void setCity(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>guide.address.city</code>.
     */
    public String getCity() {
        return (String) get(6);
    }

    /**
     * Setter for <code>guide.address.country</code>.
     */
    public void setCountry(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>guide.address.country</code>.
     */
    public String getCountry() {
        return (String) get(7);
    }

    /**
     * Setter for <code>guide.address.detail</code>.
     */
    public void setDetail(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>guide.address.detail</code>.
     */
    public String getDetail() {
        return (String) get(8);
    }

    /**
     * Setter for <code>guide.address.fix_telephone</code>.
     */
    public void setFixTelephone(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>guide.address.fix_telephone</code>.
     */
    public String getFixTelephone() {
        return (String) get(9);
    }

    /**
     * Setter for <code>guide.address.mobile</code>.
     */
    public void setMobile(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>guide.address.mobile</code>.
     */
    public String getMobile() {
        return (String) get(10);
    }

    /**
     * Setter for <code>guide.address.province</code>.
     */
    public void setProvince(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>guide.address.province</code>.
     */
    public String getProvince() {
        return (String) get(11);
    }

    /**
     * Setter for <code>guide.address.street</code>.
     */
    public void setStreet(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>guide.address.street</code>.
     */
    public String getStreet() {
        return (String) get(12);
    }

    /**
     * Setter for <code>guide.address.type</code>.
     */
    public void setType(Integer value) {
        set(13, value);
    }

    /**
     * Getter for <code>guide.address.type</code>.
     */
    public Integer getType() {
        return (Integer) get(13);
    }

    /**
     * Setter for <code>guide.address.zip_code</code>.
     */
    public void setZipCode(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>guide.address.zip_code</code>.
     */
    public String getZipCode() {
        return (String) get(14);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record15 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row15<Long, Long, LocalDateTime, Integer, Long, LocalDateTime, String, String, String, String, String, String, String, Integer, String> fieldsRow() {
        return (Row15) super.fieldsRow();
    }

    @Override
    public Row15<Long, Long, LocalDateTime, Integer, Long, LocalDateTime, String, String, String, String, String, String, String, Integer, String> valuesRow() {
        return (Row15) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Address.ADDRESS.ID;
    }

    @Override
    public Field<Long> field2() {
        return Address.ADDRESS.CREATE_BY;
    }

    @Override
    public Field<LocalDateTime> field3() {
        return Address.ADDRESS.CREATE_DT;
    }

    @Override
    public Field<Integer> field4() {
        return Address.ADDRESS.IS_DELETE;
    }

    @Override
    public Field<Long> field5() {
        return Address.ADDRESS.UPDATE_BY;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return Address.ADDRESS.UPDATE_DT;
    }

    @Override
    public Field<String> field7() {
        return Address.ADDRESS.CITY;
    }

    @Override
    public Field<String> field8() {
        return Address.ADDRESS.COUNTRY;
    }

    @Override
    public Field<String> field9() {
        return Address.ADDRESS.DETAIL;
    }

    @Override
    public Field<String> field10() {
        return Address.ADDRESS.FIX_TELEPHONE;
    }

    @Override
    public Field<String> field11() {
        return Address.ADDRESS.MOBILE;
    }

    @Override
    public Field<String> field12() {
        return Address.ADDRESS.PROVINCE;
    }

    @Override
    public Field<String> field13() {
        return Address.ADDRESS.STREET;
    }

    @Override
    public Field<Integer> field14() {
        return Address.ADDRESS.TYPE;
    }

    @Override
    public Field<String> field15() {
        return Address.ADDRESS.ZIP_CODE;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getCreateBy();
    }

    @Override
    public LocalDateTime component3() {
        return getCreateDt();
    }

    @Override
    public Integer component4() {
        return getIsDelete();
    }

    @Override
    public Long component5() {
        return getUpdateBy();
    }

    @Override
    public LocalDateTime component6() {
        return getUpdateDt();
    }

    @Override
    public String component7() {
        return getCity();
    }

    @Override
    public String component8() {
        return getCountry();
    }

    @Override
    public String component9() {
        return getDetail();
    }

    @Override
    public String component10() {
        return getFixTelephone();
    }

    @Override
    public String component11() {
        return getMobile();
    }

    @Override
    public String component12() {
        return getProvince();
    }

    @Override
    public String component13() {
        return getStreet();
    }

    @Override
    public Integer component14() {
        return getType();
    }

    @Override
    public String component15() {
        return getZipCode();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getCreateBy();
    }

    @Override
    public LocalDateTime value3() {
        return getCreateDt();
    }

    @Override
    public Integer value4() {
        return getIsDelete();
    }

    @Override
    public Long value5() {
        return getUpdateBy();
    }

    @Override
    public LocalDateTime value6() {
        return getUpdateDt();
    }

    @Override
    public String value7() {
        return getCity();
    }

    @Override
    public String value8() {
        return getCountry();
    }

    @Override
    public String value9() {
        return getDetail();
    }

    @Override
    public String value10() {
        return getFixTelephone();
    }

    @Override
    public String value11() {
        return getMobile();
    }

    @Override
    public String value12() {
        return getProvince();
    }

    @Override
    public String value13() {
        return getStreet();
    }

    @Override
    public Integer value14() {
        return getType();
    }

    @Override
    public String value15() {
        return getZipCode();
    }

    @Override
    public AddressRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public AddressRecord value2(Long value) {
        setCreateBy(value);
        return this;
    }

    @Override
    public AddressRecord value3(LocalDateTime value) {
        setCreateDt(value);
        return this;
    }

    @Override
    public AddressRecord value4(Integer value) {
        setIsDelete(value);
        return this;
    }

    @Override
    public AddressRecord value5(Long value) {
        setUpdateBy(value);
        return this;
    }

    @Override
    public AddressRecord value6(LocalDateTime value) {
        setUpdateDt(value);
        return this;
    }

    @Override
    public AddressRecord value7(String value) {
        setCity(value);
        return this;
    }

    @Override
    public AddressRecord value8(String value) {
        setCountry(value);
        return this;
    }

    @Override
    public AddressRecord value9(String value) {
        setDetail(value);
        return this;
    }

    @Override
    public AddressRecord value10(String value) {
        setFixTelephone(value);
        return this;
    }

    @Override
    public AddressRecord value11(String value) {
        setMobile(value);
        return this;
    }

    @Override
    public AddressRecord value12(String value) {
        setProvince(value);
        return this;
    }

    @Override
    public AddressRecord value13(String value) {
        setStreet(value);
        return this;
    }

    @Override
    public AddressRecord value14(Integer value) {
        setType(value);
        return this;
    }

    @Override
    public AddressRecord value15(String value) {
        setZipCode(value);
        return this;
    }

    @Override
    public AddressRecord values(Long value1, Long value2, LocalDateTime value3, Integer value4, Long value5, LocalDateTime value6, String value7, String value8, String value9, String value10, String value11, String value12, String value13, Integer value14, String value15) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AddressRecord
     */
    public AddressRecord() {
        super(Address.ADDRESS);
    }

    /**
     * Create a detached, initialised AddressRecord
     */
    public AddressRecord(Long id, Long createBy, LocalDateTime createDt, Integer isDelete, Long updateBy, LocalDateTime updateDt, String city, String country, String detail, String fixTelephone, String mobile, String province, String street, Integer type, String zipCode) {
        super(Address.ADDRESS);

        set(0, id);
        set(1, createBy);
        set(2, createDt);
        set(3, isDelete);
        set(4, updateBy);
        set(5, updateDt);
        set(6, city);
        set(7, country);
        set(8, detail);
        set(9, fixTelephone);
        set(10, mobile);
        set(11, province);
        set(12, street);
        set(13, type);
        set(14, zipCode);
    }
}
