/*
 * This file is generated by jOOQ.
 */
package com.klaus.iv.stockadmin.db.tables.records;


import com.klaus.iv.stockadmin.db.tables.StockGroup;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StockGroupRecord extends UpdatableRecordImpl<StockGroupRecord> implements Record10<Long, Long, LocalDateTime, Integer, Long, LocalDateTime, String, String, Long, String> {

    private static final long serialVersionUID = 1788297614;

    /**
     * Setter for <code>guide.stock_group.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>guide.stock_group.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>guide.stock_group.create_by</code>.
     */
    public void setCreateBy(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>guide.stock_group.create_by</code>.
     */
    public Long getCreateBy() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>guide.stock_group.create_dt</code>.
     */
    public void setCreateDt(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>guide.stock_group.create_dt</code>.
     */
    public LocalDateTime getCreateDt() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>guide.stock_group.is_delete</code>.
     */
    public void setIsDelete(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>guide.stock_group.is_delete</code>.
     */
    public Integer getIsDelete() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>guide.stock_group.update_by</code>.
     */
    public void setUpdateBy(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>guide.stock_group.update_by</code>.
     */
    public Long getUpdateBy() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>guide.stock_group.update_dt</code>.
     */
    public void setUpdateDt(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>guide.stock_group.update_dt</code>.
     */
    public LocalDateTime getUpdateDt() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>guide.stock_group.add_comments</code>.
     */
    public void setAddComments(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>guide.stock_group.add_comments</code>.
     */
    public String getAddComments() {
        return (String) get(6);
    }

    /**
     * Setter for <code>guide.stock_group.group_code</code>.
     */
    public void setGroupCode(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>guide.stock_group.group_code</code>.
     */
    public String getGroupCode() {
        return (String) get(7);
    }

    /**
     * Setter for <code>guide.stock_group.price</code>.
     */
    public void setPrice(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>guide.stock_group.price</code>.
     */
    public Long getPrice() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>guide.stock_group.stock_code</code>.
     */
    public void setStockCode(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>guide.stock_group.stock_code</code>.
     */
    public String getStockCode() {
        return (String) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row10<Long, Long, LocalDateTime, Integer, Long, LocalDateTime, String, String, Long, String> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    @Override
    public Row10<Long, Long, LocalDateTime, Integer, Long, LocalDateTime, String, String, Long, String> valuesRow() {
        return (Row10) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return StockGroup.STOCK_GROUP.ID;
    }

    @Override
    public Field<Long> field2() {
        return StockGroup.STOCK_GROUP.CREATE_BY;
    }

    @Override
    public Field<LocalDateTime> field3() {
        return StockGroup.STOCK_GROUP.CREATE_DT;
    }

    @Override
    public Field<Integer> field4() {
        return StockGroup.STOCK_GROUP.IS_DELETE;
    }

    @Override
    public Field<Long> field5() {
        return StockGroup.STOCK_GROUP.UPDATE_BY;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return StockGroup.STOCK_GROUP.UPDATE_DT;
    }

    @Override
    public Field<String> field7() {
        return StockGroup.STOCK_GROUP.ADD_COMMENTS;
    }

    @Override
    public Field<String> field8() {
        return StockGroup.STOCK_GROUP.GROUP_CODE;
    }

    @Override
    public Field<Long> field9() {
        return StockGroup.STOCK_GROUP.PRICE;
    }

    @Override
    public Field<String> field10() {
        return StockGroup.STOCK_GROUP.STOCK_CODE;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getCreateBy();
    }

    @Override
    public LocalDateTime component3() {
        return getCreateDt();
    }

    @Override
    public Integer component4() {
        return getIsDelete();
    }

    @Override
    public Long component5() {
        return getUpdateBy();
    }

    @Override
    public LocalDateTime component6() {
        return getUpdateDt();
    }

    @Override
    public String component7() {
        return getAddComments();
    }

    @Override
    public String component8() {
        return getGroupCode();
    }

    @Override
    public Long component9() {
        return getPrice();
    }

    @Override
    public String component10() {
        return getStockCode();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getCreateBy();
    }

    @Override
    public LocalDateTime value3() {
        return getCreateDt();
    }

    @Override
    public Integer value4() {
        return getIsDelete();
    }

    @Override
    public Long value5() {
        return getUpdateBy();
    }

    @Override
    public LocalDateTime value6() {
        return getUpdateDt();
    }

    @Override
    public String value7() {
        return getAddComments();
    }

    @Override
    public String value8() {
        return getGroupCode();
    }

    @Override
    public Long value9() {
        return getPrice();
    }

    @Override
    public String value10() {
        return getStockCode();
    }

    @Override
    public StockGroupRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public StockGroupRecord value2(Long value) {
        setCreateBy(value);
        return this;
    }

    @Override
    public StockGroupRecord value3(LocalDateTime value) {
        setCreateDt(value);
        return this;
    }

    @Override
    public StockGroupRecord value4(Integer value) {
        setIsDelete(value);
        return this;
    }

    @Override
    public StockGroupRecord value5(Long value) {
        setUpdateBy(value);
        return this;
    }

    @Override
    public StockGroupRecord value6(LocalDateTime value) {
        setUpdateDt(value);
        return this;
    }

    @Override
    public StockGroupRecord value7(String value) {
        setAddComments(value);
        return this;
    }

    @Override
    public StockGroupRecord value8(String value) {
        setGroupCode(value);
        return this;
    }

    @Override
    public StockGroupRecord value9(Long value) {
        setPrice(value);
        return this;
    }

    @Override
    public StockGroupRecord value10(String value) {
        setStockCode(value);
        return this;
    }

    @Override
    public StockGroupRecord values(Long value1, Long value2, LocalDateTime value3, Integer value4, Long value5, LocalDateTime value6, String value7, String value8, Long value9, String value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StockGroupRecord
     */
    public StockGroupRecord() {
        super(StockGroup.STOCK_GROUP);
    }

    /**
     * Create a detached, initialised StockGroupRecord
     */
    public StockGroupRecord(Long id, Long createBy, LocalDateTime createDt, Integer isDelete, Long updateBy, LocalDateTime updateDt, String addComments, String groupCode, Long price, String stockCode) {
        super(StockGroup.STOCK_GROUP);

        set(0, id);
        set(1, createBy);
        set(2, createDt);
        set(3, isDelete);
        set(4, updateBy);
        set(5, updateDt);
        set(6, addComments);
        set(7, groupCode);
        set(8, price);
        set(9, stockCode);
    }
}
