/*
 * This file is generated by jOOQ.
 */
package com.klaus.iv.stockadmin.db.tables.records;


import com.klaus.iv.stockadmin.db.tables.YiGroup;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class YiGroupRecord extends UpdatableRecordImpl<YiGroupRecord> implements Record9<Long, Long, LocalDateTime, Integer, Long, LocalDateTime, String, String, String> {

    private static final long serialVersionUID = 206103926;

    /**
     * Setter for <code>guide.yi_group.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>guide.yi_group.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>guide.yi_group.create_by</code>.
     */
    public void setCreateBy(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>guide.yi_group.create_by</code>.
     */
    public Long getCreateBy() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>guide.yi_group.create_dt</code>.
     */
    public void setCreateDt(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>guide.yi_group.create_dt</code>.
     */
    public LocalDateTime getCreateDt() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>guide.yi_group.is_delete</code>.
     */
    public void setIsDelete(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>guide.yi_group.is_delete</code>.
     */
    public Integer getIsDelete() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>guide.yi_group.update_by</code>.
     */
    public void setUpdateBy(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>guide.yi_group.update_by</code>.
     */
    public Long getUpdateBy() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>guide.yi_group.update_dt</code>.
     */
    public void setUpdateDt(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>guide.yi_group.update_dt</code>.
     */
    public LocalDateTime getUpdateDt() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>guide.yi_group.code</code>.
     */
    public void setCode(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>guide.yi_group.code</code>.
     */
    public String getCode() {
        return (String) get(6);
    }

    /**
     * Setter for <code>guide.yi_group.group_desc</code>.
     */
    public void setGroupDesc(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>guide.yi_group.group_desc</code>.
     */
    public String getGroupDesc() {
        return (String) get(7);
    }

    /**
     * Setter for <code>guide.yi_group.name</code>.
     */
    public void setName(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>guide.yi_group.name</code>.
     */
    public String getName() {
        return (String) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row9<Long, Long, LocalDateTime, Integer, Long, LocalDateTime, String, String, String> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    public Row9<Long, Long, LocalDateTime, Integer, Long, LocalDateTime, String, String, String> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return YiGroup.YI_GROUP.ID;
    }

    @Override
    public Field<Long> field2() {
        return YiGroup.YI_GROUP.CREATE_BY;
    }

    @Override
    public Field<LocalDateTime> field3() {
        return YiGroup.YI_GROUP.CREATE_DT;
    }

    @Override
    public Field<Integer> field4() {
        return YiGroup.YI_GROUP.IS_DELETE;
    }

    @Override
    public Field<Long> field5() {
        return YiGroup.YI_GROUP.UPDATE_BY;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return YiGroup.YI_GROUP.UPDATE_DT;
    }

    @Override
    public Field<String> field7() {
        return YiGroup.YI_GROUP.CODE;
    }

    @Override
    public Field<String> field8() {
        return YiGroup.YI_GROUP.GROUP_DESC;
    }

    @Override
    public Field<String> field9() {
        return YiGroup.YI_GROUP.NAME;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getCreateBy();
    }

    @Override
    public LocalDateTime component3() {
        return getCreateDt();
    }

    @Override
    public Integer component4() {
        return getIsDelete();
    }

    @Override
    public Long component5() {
        return getUpdateBy();
    }

    @Override
    public LocalDateTime component6() {
        return getUpdateDt();
    }

    @Override
    public String component7() {
        return getCode();
    }

    @Override
    public String component8() {
        return getGroupDesc();
    }

    @Override
    public String component9() {
        return getName();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getCreateBy();
    }

    @Override
    public LocalDateTime value3() {
        return getCreateDt();
    }

    @Override
    public Integer value4() {
        return getIsDelete();
    }

    @Override
    public Long value5() {
        return getUpdateBy();
    }

    @Override
    public LocalDateTime value6() {
        return getUpdateDt();
    }

    @Override
    public String value7() {
        return getCode();
    }

    @Override
    public String value8() {
        return getGroupDesc();
    }

    @Override
    public String value9() {
        return getName();
    }

    @Override
    public YiGroupRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public YiGroupRecord value2(Long value) {
        setCreateBy(value);
        return this;
    }

    @Override
    public YiGroupRecord value3(LocalDateTime value) {
        setCreateDt(value);
        return this;
    }

    @Override
    public YiGroupRecord value4(Integer value) {
        setIsDelete(value);
        return this;
    }

    @Override
    public YiGroupRecord value5(Long value) {
        setUpdateBy(value);
        return this;
    }

    @Override
    public YiGroupRecord value6(LocalDateTime value) {
        setUpdateDt(value);
        return this;
    }

    @Override
    public YiGroupRecord value7(String value) {
        setCode(value);
        return this;
    }

    @Override
    public YiGroupRecord value8(String value) {
        setGroupDesc(value);
        return this;
    }

    @Override
    public YiGroupRecord value9(String value) {
        setName(value);
        return this;
    }

    @Override
    public YiGroupRecord values(Long value1, Long value2, LocalDateTime value3, Integer value4, Long value5, LocalDateTime value6, String value7, String value8, String value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached YiGroupRecord
     */
    public YiGroupRecord() {
        super(YiGroup.YI_GROUP);
    }

    /**
     * Create a detached, initialised YiGroupRecord
     */
    public YiGroupRecord(Long id, Long createBy, LocalDateTime createDt, Integer isDelete, Long updateBy, LocalDateTime updateDt, String code, String groupDesc, String name) {
        super(YiGroup.YI_GROUP);

        set(0, id);
        set(1, createBy);
        set(2, createDt);
        set(3, isDelete);
        set(4, updateBy);
        set(5, updateDt);
        set(6, code);
        set(7, groupDesc);
        set(8, name);
    }
}
