server:
  port: 9000
  servlet:
    context-path: /app-admin
spring:
  application:
    name: app-admin
  devtools:
    livereload:
      port: 9200
eureka:
  instance:
    statusPageUrlPath: /info
    healthCheckUrlPath: /health
    hostname: 127.0.0.1
    instance-id: ${spring.application.name}
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:30000/eureka/
management:
  server:
    port: 9100
  endpoint:
    beans:
      enabled: true
      cache:
        time-to-live: 1000ms
    health:
      show-details: always
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"
#        exclude: