server:
  servlet:
    context-path: /app-admin
spring:
  application:
    name: ${APP_NAME:app-admin}
  profiles:
    active: local
eureka:
  instance:
    statusPageUrlPath: /info
    healthCheckUrlPath: /health
    hostname: 127.0.0.1
    instance-id: ${spring.application.name}
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://${HOST_NAME:localhost}:3000/eureka/
    enabled: true
management:
  endpoint:
    beans:
      enabled: true
      cache:
        time-to-live: 1000ms
    health:
      show-details: always
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"
#        exclude:




---
spring:
  profiles: local
  devtools:
    livereload:
      port: ${DEV_TOOLS_PORT:9201}
management:
  server:
    port: ${MANAGEMENT_PORT:9101}
server:
  port: ${APP_PORT:9001}

---
spring:
  profiles: dev
  devtools:
    livereload:
      port: ${DEV_TOOLS_PORT:9202}
management:
  server:
    port: ${MANAGEMENT_PORT:9102}
server:
  port: ${APP_PORT:9002}

---
spring:
  profiles: prod
  devtools:
    livereload:
      port: ${DEV_TOOLS_PORT:9200}
management:
  server:
    port: ${MANAGEMENT_PORT:9100}
server:
  port: ${APP_PORT:9000}