debug: false
spring:
  application:
    name: ${APP_NAME:app-admin}
  profiles:
    active: local

eureka:
  instance:
    hostname: ${HOST_NAME:127.0.0.1}
    instance-id: ${spring.application.name}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/


---
spring:
  profiles: local
server:
  port: ${APP_PORT:3000}

---
spring:
  profiles: dev
server:
  port: ${APP_PORT:3000}


---
spring:
  profiles: prod
server:
  port: ${APP_PORT:3000}