spring:
  jmx:
    enabled: true
  jackson:
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://${MYSQL_SERVER:212.129.238.215}:${MYSQL_PORT:8888}/learn?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8
    username: ENC(uSpU5irKuvMIT1mR0/2Whgh3EY9dRKwNKkZBNh2z20h4T8Le8SGPYBzC957M0hGS)
    password: ENC(Y5xuHdnuK897yMFWFJQA3ZFT7+Z4YCVvnp/st/SlgNw54YmOpD0qIYFBcmLry2Ks)
    hikari:
      pool-name: ${spring.application.name}-pool
      maximum-pool-size: 20
      minimum-idle: 3
      max-lifetime: 30000
      connection-test-query: select 1
  redis:
    host: 111.231.215.20
    port: 7777
    database: 0
    password: ENC(EY7Y4OEBEg5n/nZdeNYO1FEBAbGWrehdKyTzHNak3g3zRLFxw0BWajW6TDz0JX/K)
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql


logging:
  config: classpath:logback-spring.xml

yi:
  swagger:
    enabled: true
    title: ${spring.application.name}-文档中心
    description: this is learn-admin api documention
    contact:
      name: klaus
      url: http://github.com/olderzhou
      email: niklausjulie@gmail.com
knife4j:
  basic:
    enable: true
    username: klaus
    password: K11@us213qwe

feign:
  okhttp:
    enabled: true
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: FULL  # BASIC, FULL, HEADERS, NONE

---
spring:
  profiles: local
  devtools:
    livereload:
      port: ${DEV_TOOLS_PORT:52000}
management:
  server:
    port: ${MANAGEMENT_PORT:51000}
server:
  port: ${APP_PORT:5000}

---
spring:
  profiles: dev
  devtools:
    livereload:
      port: ${DEV_TOOLS_PORT:52001}
management:
  server:
    port: ${MANAGEMENT_PORT:51001}
server:
  port: ${APP_PORT:5001}


---
spring:
  profiles: prod
  devtools:
    livereload:
      port: ${DEV_TOOLS_PORT:52002}
management:
  server:
    port: ${MANAGEMENT_PORT:51002}
server:
  port: ${APP_PORT:5002}