/*
 * This file is generated by jOOQ.
 */
package com.klaus.iv.useradmin.db.tables.records;


import com.klaus.iv.useradmin.db.tables.RoleResource;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RoleResourceRecord extends UpdatableRecordImpl<RoleResourceRecord> implements Record8<Long, Long, LocalDateTime, Integer, Long, LocalDateTime, Long, Long> {

    private static final long serialVersionUID = -919682030;

    /**
     * Setter for <code>user_center.role_resource.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>user_center.role_resource.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>user_center.role_resource.create_by</code>.
     */
    public void setCreateBy(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>user_center.role_resource.create_by</code>.
     */
    public Long getCreateBy() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>user_center.role_resource.create_dt</code>.
     */
    public void setCreateDt(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>user_center.role_resource.create_dt</code>.
     */
    public LocalDateTime getCreateDt() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>user_center.role_resource.is_delete</code>.
     */
    public void setIsDelete(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>user_center.role_resource.is_delete</code>.
     */
    public Integer getIsDelete() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>user_center.role_resource.update_by</code>.
     */
    public void setUpdateBy(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>user_center.role_resource.update_by</code>.
     */
    public Long getUpdateBy() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>user_center.role_resource.update_dt</code>.
     */
    public void setUpdateDt(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>user_center.role_resource.update_dt</code>.
     */
    public LocalDateTime getUpdateDt() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>user_center.role_resource.resource_id</code>.
     */
    public void setResourceId(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>user_center.role_resource.resource_id</code>.
     */
    public Long getResourceId() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>user_center.role_resource.role_id</code>.
     */
    public void setRoleId(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>user_center.role_resource.role_id</code>.
     */
    public Long getRoleId() {
        return (Long) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<Long, Long, LocalDateTime, Integer, Long, LocalDateTime, Long, Long> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<Long, Long, LocalDateTime, Integer, Long, LocalDateTime, Long, Long> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return RoleResource.ROLE_RESOURCE.ID;
    }

    @Override
    public Field<Long> field2() {
        return RoleResource.ROLE_RESOURCE.CREATE_BY;
    }

    @Override
    public Field<LocalDateTime> field3() {
        return RoleResource.ROLE_RESOURCE.CREATE_DT;
    }

    @Override
    public Field<Integer> field4() {
        return RoleResource.ROLE_RESOURCE.IS_DELETE;
    }

    @Override
    public Field<Long> field5() {
        return RoleResource.ROLE_RESOURCE.UPDATE_BY;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return RoleResource.ROLE_RESOURCE.UPDATE_DT;
    }

    @Override
    public Field<Long> field7() {
        return RoleResource.ROLE_RESOURCE.RESOURCE_ID;
    }

    @Override
    public Field<Long> field8() {
        return RoleResource.ROLE_RESOURCE.ROLE_ID;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getCreateBy();
    }

    @Override
    public LocalDateTime component3() {
        return getCreateDt();
    }

    @Override
    public Integer component4() {
        return getIsDelete();
    }

    @Override
    public Long component5() {
        return getUpdateBy();
    }

    @Override
    public LocalDateTime component6() {
        return getUpdateDt();
    }

    @Override
    public Long component7() {
        return getResourceId();
    }

    @Override
    public Long component8() {
        return getRoleId();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getCreateBy();
    }

    @Override
    public LocalDateTime value3() {
        return getCreateDt();
    }

    @Override
    public Integer value4() {
        return getIsDelete();
    }

    @Override
    public Long value5() {
        return getUpdateBy();
    }

    @Override
    public LocalDateTime value6() {
        return getUpdateDt();
    }

    @Override
    public Long value7() {
        return getResourceId();
    }

    @Override
    public Long value8() {
        return getRoleId();
    }

    @Override
    public RoleResourceRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public RoleResourceRecord value2(Long value) {
        setCreateBy(value);
        return this;
    }

    @Override
    public RoleResourceRecord value3(LocalDateTime value) {
        setCreateDt(value);
        return this;
    }

    @Override
    public RoleResourceRecord value4(Integer value) {
        setIsDelete(value);
        return this;
    }

    @Override
    public RoleResourceRecord value5(Long value) {
        setUpdateBy(value);
        return this;
    }

    @Override
    public RoleResourceRecord value6(LocalDateTime value) {
        setUpdateDt(value);
        return this;
    }

    @Override
    public RoleResourceRecord value7(Long value) {
        setResourceId(value);
        return this;
    }

    @Override
    public RoleResourceRecord value8(Long value) {
        setRoleId(value);
        return this;
    }

    @Override
    public RoleResourceRecord values(Long value1, Long value2, LocalDateTime value3, Integer value4, Long value5, LocalDateTime value6, Long value7, Long value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RoleResourceRecord
     */
    public RoleResourceRecord() {
        super(RoleResource.ROLE_RESOURCE);
    }

    /**
     * Create a detached, initialised RoleResourceRecord
     */
    public RoleResourceRecord(Long id, Long createBy, LocalDateTime createDt, Integer isDelete, Long updateBy, LocalDateTime updateDt, Long resourceId, Long roleId) {
        super(RoleResource.ROLE_RESOURCE);

        set(0, id);
        set(1, createBy);
        set(2, createDt);
        set(3, isDelete);
        set(4, updateBy);
        set(5, updateDt);
        set(6, resourceId);
        set(7, roleId);
    }
}
