server:
  port: 4000
#  servlet:
#    context-path: /app-user
spring:
  application:
    name: app-user
  devtools:
    livereload:
      port: 41000
eureka:
  instance:
    statusPageUrlPath: /info
    healthCheckUrlPath: /health
    hostname: 127.0.0.1
    instance-id: ${spring.application.name}
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:3000/eureka/
management:
  server:
    port: 41000
  endpoint:
    beans:
      enabled: true
      cache:
        time-to-live: 1000ms
    health:
      show-details: always
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"
#        exclude: