/*
 * This file is generated by jOOQ.
 */
package com.klaus.iv.stockadmin.db;


import com.klaus.iv.stockadmin.db.tables.Address;
import com.klaus.iv.stockadmin.db.tables.Resource;
import com.klaus.iv.stockadmin.db.tables.Role;
import com.klaus.iv.stockadmin.db.tables.RoleResource;
import com.klaus.iv.stockadmin.db.tables.Stock;
import com.klaus.iv.stockadmin.db.tables.StockGroup;
import com.klaus.iv.stockadmin.db.tables.StockPo;
import com.klaus.iv.stockadmin.db.tables.User;
import com.klaus.iv.stockadmin.db.tables.UserAddress;
import com.klaus.iv.stockadmin.db.tables.UserExt;
import com.klaus.iv.stockadmin.db.tables.UserGroup;
import com.klaus.iv.stockadmin.db.tables.UserRole;
import com.klaus.iv.stockadmin.db.tables.YiGroup;
import com.klaus.iv.stockadmin.db.tables.YiStock;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Guide extends SchemaImpl {

    private static final long serialVersionUID = 103239073;

    /**
     * The reference instance of <code>guide</code>
     */
    public static final Guide GUIDE = new Guide();

    /**
     * The table <code>guide.address</code>.
     */
    public final Address ADDRESS = Address.ADDRESS;

    /**
     * The table <code>guide.resource</code>.
     */
    public final Resource RESOURCE = Resource.RESOURCE;

    /**
     * The table <code>guide.role</code>.
     */
    public final Role ROLE = Role.ROLE;

    /**
     * The table <code>guide.role_resource</code>.
     */
    public final RoleResource ROLE_RESOURCE = RoleResource.ROLE_RESOURCE;

    /**
     * The table <code>guide.stock</code>.
     */
    public final Stock STOCK = Stock.STOCK;

    /**
     * The table <code>guide.stock_group</code>.
     */
    public final StockGroup STOCK_GROUP = StockGroup.STOCK_GROUP;

    /**
     * The table <code>guide.stock_po</code>.
     */
    public final StockPo STOCK_PO = StockPo.STOCK_PO;

    /**
     * The table <code>guide.user</code>.
     */
    public final User USER = User.USER;

    /**
     * The table <code>guide.user_address</code>.
     */
    public final UserAddress USER_ADDRESS = UserAddress.USER_ADDRESS;

    /**
     * The table <code>guide.user_ext</code>.
     */
    public final UserExt USER_EXT = UserExt.USER_EXT;

    /**
     * The table <code>guide.user_group</code>.
     */
    public final UserGroup USER_GROUP = UserGroup.USER_GROUP;

    /**
     * The table <code>guide.user_role</code>.
     */
    public final UserRole USER_ROLE = UserRole.USER_ROLE;

    /**
     * The table <code>guide.yi_group</code>.
     */
    public final YiGroup YI_GROUP = YiGroup.YI_GROUP;

    /**
     * The table <code>guide.yi_stock</code>.
     */
    public final YiStock YI_STOCK = YiStock.YI_STOCK;

    /**
     * No further instances allowed
     */
    private Guide() {
        super("guide", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Address.ADDRESS,
            Resource.RESOURCE,
            Role.ROLE,
            RoleResource.ROLE_RESOURCE,
            Stock.STOCK,
            StockGroup.STOCK_GROUP,
            StockPo.STOCK_PO,
            User.USER,
            UserAddress.USER_ADDRESS,
            UserExt.USER_EXT,
            UserGroup.USER_GROUP,
            UserRole.USER_ROLE,
            YiGroup.YI_GROUP,
            YiStock.YI_STOCK);
    }
}
