/*
 * This file is generated by jOOQ.
 */
package com.klaus.iv.stockadmin.db;


import com.klaus.iv.stockadmin.db.tables.Address;
import com.klaus.iv.stockadmin.db.tables.Resource;
import com.klaus.iv.stockadmin.db.tables.Role;
import com.klaus.iv.stockadmin.db.tables.RoleResource;
import com.klaus.iv.stockadmin.db.tables.Stock;
import com.klaus.iv.stockadmin.db.tables.StockGroup;
import com.klaus.iv.stockadmin.db.tables.StockPo;
import com.klaus.iv.stockadmin.db.tables.User;
import com.klaus.iv.stockadmin.db.tables.UserAddress;
import com.klaus.iv.stockadmin.db.tables.UserExt;
import com.klaus.iv.stockadmin.db.tables.UserGroup;
import com.klaus.iv.stockadmin.db.tables.UserRole;
import com.klaus.iv.stockadmin.db.tables.YiGroup;
import com.klaus.iv.stockadmin.db.tables.YiStock;


/**
 * Convenience access to all tables in guide
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>guide.address</code>.
     */
    public static final Address ADDRESS = Address.ADDRESS;

    /**
     * The table <code>guide.resource</code>.
     */
    public static final Resource RESOURCE = Resource.RESOURCE;

    /**
     * The table <code>guide.role</code>.
     */
    public static final Role ROLE = Role.ROLE;

    /**
     * The table <code>guide.role_resource</code>.
     */
    public static final RoleResource ROLE_RESOURCE = RoleResource.ROLE_RESOURCE;

    /**
     * The table <code>guide.stock</code>.
     */
    public static final Stock STOCK = Stock.STOCK;

    /**
     * The table <code>guide.stock_group</code>.
     */
    public static final StockGroup STOCK_GROUP = StockGroup.STOCK_GROUP;

    /**
     * The table <code>guide.stock_po</code>.
     */
    public static final StockPo STOCK_PO = StockPo.STOCK_PO;

    /**
     * The table <code>guide.user</code>.
     */
    public static final User USER = User.USER;

    /**
     * The table <code>guide.user_address</code>.
     */
    public static final UserAddress USER_ADDRESS = UserAddress.USER_ADDRESS;

    /**
     * The table <code>guide.user_ext</code>.
     */
    public static final UserExt USER_EXT = UserExt.USER_EXT;

    /**
     * The table <code>guide.user_group</code>.
     */
    public static final UserGroup USER_GROUP = UserGroup.USER_GROUP;

    /**
     * The table <code>guide.user_role</code>.
     */
    public static final UserRole USER_ROLE = UserRole.USER_ROLE;

    /**
     * The table <code>guide.yi_group</code>.
     */
    public static final YiGroup YI_GROUP = YiGroup.YI_GROUP;

    /**
     * The table <code>guide.yi_stock</code>.
     */
    public static final YiStock YI_STOCK = YiStock.YI_STOCK;
}
