test:
  #  hostport: httpbin.org:80
  #  hostport: localhost:5000
  app-user-uri: http://127.0.0.1:4000
  app-admin-uri: http://127.0.0.1:9000
  app-user: lb://appuser
  app-admin: lb://app-admin

spring:
  application:
    name: app-gateway
  profiles:
    active: local
  cloud:
    gateway:
      routes:
      - id: app-admin-service
        uri: ${test.app-admin-uri}
        predicates:
        - Path=/app-admin/**
        filters:
        - name: RequestRateLimiter
          args:
            redis-rate-limiter.replenishRate: 3
            redis-rate-limiter.burstCapacity: 10
            redis-rate-limiter.requestedTokens: 60
      - id: app-user-service
        uri: ${test.app-user}
        predicates:
          - Path=/app-user/**
        filters:
          - name: RequestRateLimiter
            args:
              redis-rate-limiter.replenishRate: 3
              redis-rate-limiter.burstCapacity: 10
              redis-rate-limiter.requestedTokens: 60
#      - id: myRoute
#        uri: lb://service
#        predicates:
#          - Path=/service/**
      filter:
        request-rate-limiter:
          deny-empty-key: false
      # 全局corl配置
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://yitech.club"
            allowedMethods:
              - GET
  jmx:
    enabled: true
  redis:
    host: 111.231.215.20
    port: 7777
    database: 0
    password: ENC(EY7Y4OEBEg5n/nZdeNYO1FEBAbGWrehdKyTzHNak3g3zRLFxw0BWajW6TDz0JX/K)

eureka:
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://${HOST_NAME:localhost}:3000/eureka/
  instance:
    instance-id: ${spring.application.name}
    hostname: 127.0.0.1



management:
  trace:
    http:
      enabled: true
      include:
        - principal
        - remote-address
        - session-id
        - time-taken
        - cookie-headers
  metrics:
    enable:
      jvm: true
      hibernate: true
  endpoint:
    beans:
      enabled: true
      cache:
        time-to-live: 30s
    health:
      show-details: always
    shutdown:
      enabled: true
    jolokia:
      enabled: true
      config:
        debug: true
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"
        exclude: env,beans

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG


---
spring:
  profiles: local
  devtools:
    livereload:
      port: ${DEV_TOOLS_PORT:12000}
management:
  server:
    port: ${MANAGEMENT_PORT:11000}
server:
  port: ${APP_PORT:1000}

---
spring:
  profiles: dev
  devtools:
    livereload:
      port: ${DEV_TOOLS_PORT:12000}
management:
  server:
    port: ${MANAGEMENT_PORT:11000}
server:
  port: ${APP_PORT:1000}


---
spring:
  profiles: prod
  devtools:
    livereload:
      port: ${DEV_TOOLS_PORT:12000}
management:
  server:
    port: ${MANAGEMENT_PORT:11000}
server:
  port: ${APP_PORT:1000}